/*
 * This file is part of LiquidBounce (https://github.com/CCBlueX/LiquidBounce)
 *
 * Copyright (c) 2015 - 2025 CCBlueX
 *
 * LiquidBounce is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LiquidBounce is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LiquidBounce. If not, see <https://www.gnu.org/licenses/>.
 */
package net.ccbluex.liquidbounce.features.module.modules.player.autoshop.utils

/**
 * General indices for common colorful blocks in BedWars.
 * It's not MC 1.8.9 anymore and each colorful block has its own ID. :)
 * This concept allows AutoShop to buy, let's say wool blocks,
 * no matter what team the player is playing,
 * without detecting the team of the player.
 */
const val WOOL_ID               = "wool"
const val TERRACOTTA_ID         = "terracotta"
const val STAINED_GLASS_ID      = "stained_glass"
const val CONCRETE_ID           = "concrete"

/**
 * Prefixes used in custom indices generated by AutoShop,
 * when grouping potions by their effects, because
 * each potion has the same ID no matter what its effects are.
 */
const val POTION_PREFIX         = "potion:"         // Example: potion:speed::1
const val SPLASH_POTION_PREFIX  = "splash_potion:"  // Example: splash_potion:strength::2

/**
 * With the concept of AutoShop being to buy items using other items,
 * and the player's experience level serving as the currency
 * in some BedWars implementations,
 * the experience level is treated like an item
 * and has its own ID in order to be stored with other items
 * in the same collection.
 */
const val EXPERIENCE_ID         = "experience"

/**
 * Part of custom indices generated by AutoShop,
 * when tracking items with tiers.
 */
const val TIER_ID               = ":tier"           // Example: sword:tier::2

/**
 * Part of custom indices generated by AutoShop,
 * when tracking items with tiers, enchantments, potion effects.
 */
const val LEVEL_PREFIX          = "::"              // Example: bow:power::2

/**
 * The items, currencies, mainly used to buy other items in BedWars.
 *
 * A server will take them from the player if the latter wants to buy something.
 */
val CURRENCY_ITEMS = setOf(
    "brick", "iron_ingot", "gold_ingot", "diamond", "emerald", EXPERIENCE_ID
)


/**
 * Returns a map of items from [items] that are better than [target].
 *
 * An item is considered better than [target] if:
 * - It has the same enchantment, potion effect, or tier with a higher level.
 */
fun betterItemsOf(target: String, items: Map<String, Int>) : Map<String, Int> {
    if (!target.contains(LEVEL_PREFIX)) {
        return emptyMap()
    }

    val targetBase = target.substringBefore(LEVEL_PREFIX)
    val targetLevel = target.substringAfterLast(LEVEL_PREFIX).toIntOrNull() ?: return emptyMap()

    return items.filterKeys {
        it.contains(LEVEL_PREFIX) &&
            it.substringBefore(LEVEL_PREFIX) == targetBase &&
            (it.substringAfterLast(LEVEL_PREFIX).toIntOrNull() ?: 0) > targetLevel
    }
}

/**
 * Checks if the provided parameters are valid.
 * If they aren't, it will throw an `IllegalArgumentException`.
 *
 * @throws IllegalArgumentException
 *
 * @see net.ccbluex.liquidbounce.features.module.modules.player.autoshop.ModuleAutoShop.getRequiredClicks
 */
fun checkRequirements(
    amountPerClick: Int,
    currentCurrencyItems: Map<String, Int>,
    requiredCurrencyItems: Map<String, Int>
) {
    val requirements = arrayOf(
        (amountPerClick > 0) to
            "amountPerClick must be a positive integer!",

        currentCurrencyItems.all { it.value >= 0 } to
            "currentCurrencyItems must contain only non-negative integers!",

        requiredCurrencyItems.all { it.value > 0 } to
            "requiredCurrencyItems must contain only positive integers!",

        currentCurrencyItems.all { it.key in CURRENCY_ITEMS } to
            "currentCurrencyItems must contain only currency items!",

        requiredCurrencyItems.all { it.key in CURRENCY_ITEMS } to
            "requiredCurrencyItems must contain only currency items!",
    )

    val failedRequirements = requirements
        .filter { (isValid, _) -> !isValid }
        .map { (_, message) -> message }

    require(requirements.all { (isValid, _) -> isValid }) { failedRequirements.joinToString(", ") }
}
